### ISSUE TITLE
Performance report

### ISSUE THREAD

**Issue by andrewhampton** [skroutz/rspecq#29]
Hi! 👋 I ported our tests from `parallel_test` to `rspecq` to see if it might be a viable alternative for us. The architecture of a central test queue is something I've been looking for in ruby testing for some time, and I'm optimistic about the future for this gem. So this isn't a bug report, but a performance report that I thought you might find useful.

First, here's a little background info. Our unit tests run in our Kubernetes staging cluster, on 16 core AWS EC2 machines. In `parallel_test`, it typically takes around 8 minutes and 30 seconds to complete, give or take 15 seconds.

To test, I wrote a runner script, `rspecq_runner`, and a wrapper script, `rspecq`, to spin up various threads.

### `rspecq_runner`

```bash 
#!/bin/bash

echo "Setting up database $TEST_ENV_NUMBER..."
bin/rails db:setup &> /dev/null

echo "Running tests $TEST_ENV_NUMBER..."
bundle exec rspecq --build=$TEST_ID --update-timings --worker=$TEST_ENV_NUMBER spec/

echo "Dropping database $TEST_ENV_NUMBER..."
bin/rails db:drop &> /dev/null 
```

### `rspecq`

```bash
 #!/bin/bash

# By default, run one rspecq runner per CPU thread
CPU_COUNT=$(getconf _NPROCESSORS_ONLN)
TEST_ID=$RANDOM

# Uncomment to hard code how many rsqecq runners you want
# CPU_COUNT=14

echo "Starting test $RANDOM"

for i in $(seq $CPU_COUNT); do
   # TEST_ENV_NUMBER is used to ensure each thread connects to its own Redis and DB instance 
   export TEST_ENV_NUMBER=$i
   export TEST_ID
   ./bin/rspecq_runner &
done

bundle exec rspecq --build=$TEST_ID --report

echo "done" 
```

## Results
First, I let the tests run a couple times on each of our test servers. This was done to ensure timings were stored in Redis. I then ran our test suite 8 times to see how long it took. Here's what I found:

| Test run time |
|--------------|
| 15:30|
| 15:32|
| 14:55
14:41|
| 16:01|
| 15:13|
| 16:04|
| 15:27|

I then wanted to ensure I wasn't overloading the test machine, so I slowly incremented the number of runners:

| `CPU_COUNT` | runtime |
|---------|---------|
| 2 | 27:07 |
| 4 | 19:26 |
| 6 | 17:18 |
| 8 | 16:25 |
| 10 | 16:15 |
| 12 | 15:47 |
| 14 | 15:15 |

## Final thoughts
I was hoping for a quick port and magically everything would be faster. Turns out, there are no silver bullets.

As you can see from the numbers, it looks like a simple port from `parallel_test` to `rspecq` would nearly double our CI time.

One option I do find interesting is spinning up runner pods that connect to a central Redis. This would allow us to distribute the CI load across our k8s cluster more evenly. I assume this would also scale better horizontally, and trade cluster CPU time for test speed without vertically scaling our EC2 instances.. However, this seems like quite a bit more effort, and I won't have time to pursue this short term.

Thanks again for working on this gem. As I said before, I'm still optimistic about the future of rspecq. It was very easy to get up and running. If the runtimes were comparable, I would advocate internally for an immediate switch.

**Comment by agis** [comment]
Hello @andrewhampton! First of all, thanks for trying out rspecq and sharing the results - they're pretty interesting.

I'm not very familiar with parallel_tests, experiencing 2x slower build times with rspecq is certainly unexpected. As to why this might happen, I have some thoughts:

1. as rspecq heavily uses Redis under the hood, please ensure that Redis network latency is not the bottleneck here (e.g. is Redis located at the same network as the runners? what's the actual latency when doing a `ping` from a worker to the Redis host?)
1. try disabling persistence completely in the redis instance (see [here](https://redis.io/topics/persistence)) to rule out latency due to disk IO
1. as rspecq automatically retries flaky tests, try running the workers with `--max-requeues=0` to rule out latency due to retries
1. I'm not sure how parallel_tests schedules the tests (whole spec files or individual examples), but try passing `--file-split-threshold=840` to the workers (when running with 14 cores)
1. only use `--update-timings` once, since it incurs some slight overhead (1 additional Redis operation for every job)
1. what happens if you increase the workers to a value greater than the number of cores (e.g. 18-20)? does performance start diminishing?
1. can you try comparing parallel_tests and rspecq in your local workstation, with the same number of workers?
1. last but not least, ensure that the number of executed jobs printed by the reporter matches that of parallel_tests, to rule out any mis-configuration issues that would cause jobs to not execute correctly/be executed twice

Some questions as well:

1. how much processes you use with parallel_tests?
1. how do you measure how much time rspecq takes to complete?
1. what is the time the build takes to complete, as printed by the reporter? (hint: these results are also persisted in the `build_timings` Redis key)
1. I assume you run a single Redis instance that all workers use, right?
1. kinda obvious but I have to ask: you also run the `db:setup/drop` steps in parallel_tests?
1. in what kind of machine is Redis hosted (specs)? We have to ensure that Redis is not the bottleneck. You can use `INFO` to find out some useful statistics which might give you some hints
1. AFAIK parallel_tests also spins up a separate process, right?

Ultimately, so much disparity in build times is certainly strange and not expected. It really needs more investigation to figure it out.

**Comment by agis** [comment]
Also, rspecq makes sense when you want to squeeze more performance than what a single host can give you. For example, we run builds across 4 hosts, running 20 workers each (for a total of 80 workers).

I wouldn't expect rspecq builds to be significantly faster than parallel_tests if we're talking for a single host. Actually, they could be slightly slower (due to Redis IO).

That said, there's one case where it can still speed up your build even in a single host - that's when a single spec file dominates the build time, causing one worker to execute that slow file when others are sitting idle. In that case, the ["Spec file splitting"](https://github.com/skroutz/rspecq#spec-file-splitting) feature should speed up the build vs. parallel_tests (which I think doesn't do something similar). That's the reason I suggested bullet no. 4 above.

**Comment by andrewhampton** [comment]
Thanks for the ideas @agis! Made most of the changes you suggested and here are the results (all with 16 cores in use):

| Change | Test run time |
|---------|--------------|
| --max-requeues=0 | 15:54 |
| --update-timings on only one runner | 15:50 |
| --file-split-threshold=840 | 14:47 |
| 18 workers | 16:56 |
| 20 workers| 15:49 |

Note, these changes were cumulative, so the `--file-split-threshold` change also included the `--max-requeueues` and `--update-timings` changes.

Redis and MySQL both run on the same host as the tests. This is true for both parallel_test and rspecq. The one big difference is the load on the redis instance is pretty minimal in in parallel_test.

I'll give disabling redis persistence a shot, but that will take me a bit more time to get set up.

Regarding test splitting, parallel_test also tracks runtimes, but stores the results in a file. We manually update that file periodically.

Here are the answers to your questions:
> 1. how much processes you use with parallel_tests?
16 for both gems. Sorry if that wasn't clear, but the first set of timings in my original post were with all 16 cores available to run tests.

> 2. how do you measure how much time rspecq takes to complete?
Based on the time the step takes in GitHub actions.

> 3. what is the time the build takes to complete, as printed by the reporter? (hint: these results are also persisted in the build_timings Redis key)
These are consistently about 20s less than the times I've reported. The times I've reported for both rspecq and parallel_test include the db setup/drop.

> 4. I assume you run a single Redis instance that all workers use, right?
Correct. They're all running on the same host and pointing to the local redis.

> 5. kinda obvious but I have to ask: you also run the db:setup/drop steps in parallel_tests?
Yup 😄 

> 6. in what kind of machine is Redis hosted (specs)? We have to . ensure that Redis is not the bottleneck. You can use INFO to find out some useful statistics which might give you some hints
Redis, MySQL and the tests are all running on a EC2 m5.4xlarge instance.

> 7. afaik parallel_tests also spins up a separate process, right?
Correct. The relevant difference is parallel_tests splits the tests up front based on the timings file. The timings file is stored in the repo and must be manually updated periodically.

> Also, rspecq makes sense when you want to squeeze more performance than what a single host can give you. For example, we run builds across 4 hosts, running 20 workers each (for a total of 80 workers).

Absolutely! As I mentioned near the end of my original ~book~ post, this possibility is very appealing to me. Not only could it speed up testing, it could more evenly distribute the load across our staging cluster.

> I wouldn't expect rspecq builds to be significantly faster than parallel_tests if we're talking for a single host. Actually, they could be slightly slower (due to Redis IO).

Yeah, I'm fine with that. If the timings are similar it would prevent us from needing to manually keep the test timings file up to date. It would also position us to spread the load across the cluster.

**Comment by agis** [comment]
So the Redis instance is actually used by the tests themselves (I mean, in addition to rspecq)? If so, it may be a source of contention. Can you verify this is not the case?

Another idea: what's the `maxmemory` and `maxmemory-policy` of your Redis instance? Also what's the available amount of memory in the system? If not enough memory is present that could also cause additional Redis operations which slow down the suites.

And a question: does parallel_tests works with whole spec files (see suggestion ? or it may split them by individual examples? The results hint that `--file-split-threshold` did make things a bit faster; that _may_ suggest that the build time is dominated by a slow spec file. To verify that, you can share the contents of the `timings` key (if that's acceptable, you can send it by email or something). You can do so with the following redis command: `zrange timings 0 -1 withscores`.

> I'll give disabling redis persistence a shot, but that will take me a bit more time to get set up.

This is an important one, you have to ensure that Redis doesn't hit the disk since that would incur a major performance overhead. Could you share the Redis logs during a build?

Lastly, a kind reminder for the rest of my suggestions: (2), (3), (8) and (9).

Apparently there are many things at play here 😅

**Comment by andrewhampton** [comment]
> So the Redis instance is actually used by the tests themselves (I mean, in addition to rspecq)?

Unfortunately yes. We've got a 12 year old rails app, and there's still a little legacy code around that uses redis directly instead of `Rails.cache`. The latter is configured to be an in memory store in the test env.

Here's the output of the Redis commands you mentioned. These are just from one of the CI servers, but I assume the others would be similar.

<details><summary>INFO</summary>

```
# Server
redis_version:6.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:19d4277f1e8a2fed
redis_mode:standalone
os:Linux 4.14.181-140.257.amzn2.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:7bdcb0697070c1aa7ef05151a56d171976d1df8d
tcp_port:6379
uptime_in_seconds:55231
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:5131931
executable:/data/redis-server
config_file:

# Clients
connected_clients:2
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:6990144
used_memory_human:6.67M
used_memory_rss:14753792
used_memory_rss_human:14.07M
used_memory_peak:11178792
used_memory_peak_human:10.66M
used_memory_peak_perc:62.53%
used_memory_overhead:918820
used_memory_startup:871056
used_memory_dataset:6071324
used_memory_dataset_perc:99.22%
allocator_allocated:7071464
allocator_active:7847936
allocator_resident:11403264
total_system_memory:66712760320
total_system_memory_human:62.13G
used_memory_lua:58368
used_memory_lua_human:57.00K
used_memory_scripts:3488
used_memory_scripts_human:3.41K
number_of_cached_scripts:8
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.11
allocator_frag_bytes:776472
allocator_rss_ratio:1.45
allocator_rss_bytes:3555328
rss_overhead_ratio:1.29
rss_overhead_bytes:3350528
mem_fragmentation_ratio:2.12
mem_fragmentation_bytes:7806160
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:33972
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1099825
rdb_bgsave_in_progress:0
rdb_last_save_time:1598912220
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:1984
total_commands_processed:7782452
instantaneous_ops_per_sec:0
total_net_input_bytes:702970775
total_net_output_bytes:1306019111
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:270
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:900
evicted_keys:0
keyspace_hits:2082831
keyspace_misses:1982519
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0

# Replication
role:master
connected_slaves:0
master_replid:ff2acd1fa85eba383cf7f8d1d7350865349d7b3b
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:93.125807
used_cpu_user:72.748201
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=63,expires=0,avg_ttl=0
db1:keys=21,expires=1,avg_ttl=1209284842
db3:keys=5,expires=0,avg_ttl=0
db4:keys=13,expires=2,avg_ttl=11190200
db5:keys=5,expires=0,avg_ttl=0
db6:keys=5,expires=0,avg_ttl=0
db7:keys=12,expires=1,avg_ttl=20961875
db8:keys=18,expires=1,avg_ttl=1208970075
db9:keys=18,expires=4,avg_ttl=604151394
db10:keys=5,expires=0,avg_ttl=0
db13:keys=9,expires=1,avg_ttl=1208960775
db17:keys=4,expires=4,avg_ttl=603035950


```
</details>


<details><summary>INFO commandstats</summary>

```
# Commandstats
cmdstat_expire:calls=269551,usec=500584,usec_per_call=1.86cmdstat_hget:calls=77478,usec=121569,usec_per_call=1.57cmdstat_select:calls=1913,usec=1753,usec_per_call=0.92cmdstat_hdel:calls=11500,usec=48459,usec_per_call=4.21cmdstat_sunion:calls=139,usec=754,usec_per_call=5.42cmdstat_set:calls=1832,usec=5753,usec_per_call=3.14cmdstat_command:calls=1,usec=443,usec_per_call=443.00cmdstat_scard:calls=4724,usec=3100,usec_per_call=0.66cmdstat_exec:calls=434874,usec=682495,usec_per_call=1.57cmdstat_multi:calls=434874,usec=89543,usec_per_call=0.21
cmdstat_zcard:calls=139,usec=159,usec_per_call=1.14
cmdstat_hexists:calls=72356,usec=147132,usec_per_call=2.03
cmdstat_hgetall:calls=502264,usec=1799065,usec_per_call=3.58
cmdstat_config:calls=7368,usec=150077,usec_per_call=20.37
cmdstat_slowlog:calls=3684,usec=90616,usec_per_call=24.60
cmdstat_lrem:calls=1292,usec=3139,usec_per_call=2.43
cmdstat_incrby:calls=9363,usec=35542,usec_per_call=3.80
cmdstat_lpop:calls=414214,usec=128275,usec_per_call=0.31
cmdstat_lrange:calls=20019,usec=49799,usec_per_call=2.49
cmdstat_zadd:calls=16283,usec=152528,usec_per_call=9.37
cmdstat_evalsha:calls=11969,usec=353132,usec_per_call=29.50
cmdstat_getset:calls=56337,usec=158641,usec_per_call=2.82
cmdstat_smembers:calls=519,usec=4647,usec_per_call=8.95
cmdstat_ltrim:calls=6500,usec=11798,usec_per_call=1.82
cmdstat_incr:calls=178569,usec=444211,usec_per_call=2.49
cmdstat_pfadd:calls=5196,usec=16656,usec_per_call=3.21
cmdstat_keys:calls=241,usec=877,usec_per_call=3.64
cmdstat_zrangebyscore:calls=414995,usec=297306,usec_per_call=0.72
cmdstat_lpush:calls=5293,usec=10175,usec_per_call=1.92
cmdstat_scan:calls=324,usec=1165,usec_per_call=3.60
cmdstat_type:calls=2756,usec=3121,usec_per_call=1.13
cmdstat_rpush:calls=6036,usec=18316,usec_per_call=3.03
cmdstat_setex:calls=105364,usec=303985,usec_per_call=2.89
cmdstat_time:calls=417436,usec=192775,usec_per_call=0.46
cmdstat_sismember:calls=5206,usec=5071,usec_per_call=0.97
cmdstat_hmget:calls=36,usec=59,usec_per_call=1.64
cmdstat_get:calls=1923348,usec=2267774,usec_per_call=1.18
cmdstat_flushdb:calls=408672,usec=4893517,usec_per_call=11.97
cmdstat_zrevrange:calls=3752,usec=12784,usec_per_call=3.41
cmdstat_exists:calls=116504,usec=187103,usec_per_call=1.61
cmdstat_client:calls=173,usec=350,usec_per_call=2.02
cmdstat_llen:calls=426322,usec=130717,usec_per_call=0.31
cmdstat_eval:calls=828428,usec=5671628,usec_per_call=6.85
cmdstat_script:calls=1850,usec=7911,usec_per_call=4.28
cmdstat_srem:calls=52,usec=76,usec_per_call=1.46
cmdstat_decr:calls=126,usec=203,usec_per_call=1.61
cmdstat_hset:calls=63648,usec=244229,usec_per_call=3.84
cmdstat_info:calls=3685,usec=309553,usec_per_call=84.00
cmdstat_mget:calls=224,usec=388,usec_per_call=1.73
cmdstat_zscore:calls=15899,usec=94527,usec_per_call=5.95
cmdstat_zrem:calls=52,usec=68,usec_per_call=1.31
cmdstat_hkeys:calls=84,usec=170,usec_per_call=2.02
cmdstat_hincrby:calls=10604,usec=40443,usec_per_call=3.81
cmdstat_del:calls=22689,usec=37793,usec_per_call=1.67
cmdstat_hlen:calls=421159,usec=130444,usec_per_call=0.31
cmdstat_ttl:calls=171,usec=270,usec_per_call=1.58
cmdstat_hmset:calls=13157,usec=102276,usec_per_call=7.77
cmdstat_setnx:calls=57,usec=208,usec_per_call=3.65
cmdstat_zremrangebyscore:calls=1161,usec=6339,usec_per_call=5.46
```

</details>

So `maxmemory` is 0 and `maxmemory_policy` is noeviction. And it looks like peak used is a little under 11MB.

> And a question: does parallel_tests works with whole spec files

Yes, it splits test at the file level. The test set I'm using for this experiment is about 1100 test files. Here's a basic breakdown of how long each take according to the timings file we use for parallel_test:

| Time | Count |
|---|---|
|> 100s | 4|
| 20-100s| 29 |
| 10-20s | 60|
| 1-10s | ~350 |
| <1s | ~650 |

`zrange timing 0 -1 withscores` shows slightly better times. Only 1 is over 100s, and 9 are over 20s. I'm not sure what's causing that. It hints at the extra time not being cause during the tests themselves, but the orchestration.

As you suggested, I ran each each gem locally on a subset of the tests, and here are the timings:

| rspecq | parallel_test |
|--------|-------------|
|6:09|5:32|
|6:41|6:14|
|6:19|5:53|

As you can see, parallel_test was a slightly faster, but nowhere near the 2x I saw in the CI environment. 

I also turned off persistence for Redis in the CI environment, as well as disabled the logging. This didn't change the times much in CI. They still floated around the 15 minute mark.

I also verified the the same number of runners were working on both gems.

Sorry, I didn't intend for this to turn into a support ticket. I really appreciate the ideas for things to try though. Based on the results from running a subset locally and the timings in `zrange timing 0 -1 withscores`, it feels like an environment specific issue, causing test coordination to go much slower.

**Comment by agis** [comment]
So I'm wondering if this is due to Redis experiencing high load due to the number of clients in it. Can you issue a `INFO` _while the build is running_ (from your previous snippet I get that the command wasn't issued during a build, since I see `connected_clients:2`)? Or inspect the CPU usage of the redis-server process (using `top` or something)?

**Comment by andrewhampton** [comment]
Hey @agis, sorry to leave you hanging there. Had other production issues that took up the rest of my week and a new project is now starting, so I won't have time to follow up here anytime soon. Feel free to close out the issue if you'd like. I may have a chance to come back to this in a couple months, but I'll continue to watch the releases. As I mentioned before, this gem is very exciting to me, and I'm very optimistic about its future! Great work so far! 🚀

**Comment by agis** [comment]
Cool @andrewhampton! If you need more assistance in the future, you can follow up and we'll re-open the issue.

The takeaway here is that:

- so much difference between parallel_tests and rspecq is certainly not expected
- this is most certainly a configuration/setup issue (e.g. network latency between Redis)
- in the future, a reproduction test suite would definitely help

Thanks again!
